# Generated by Django 4.2.16 on 2026-06-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del ciclo')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL amigable')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('orden', models.IntegerField(default=0, help_text='Orden cronológico (menor = más antiguo)')),
                ('es_especial', models.BooleanField(default=False, verbose_name='¿Es evento especial?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('periodo_inicio', models.CharField(blank=True, max_length=100, verbose_name='Período inicio')),
                ('periodo_fin', models.CharField(blank=True, max_length=100, verbose_name='Período fin')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden cronológico')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pelicula', models.CharField(max_length=300, verbose_name='Título de la película')),
                ('director', models.CharField(blank=True, max_length=300, verbose_name='Director/a')),
                ('año', models.CharField(blank=True, max_length=20, verbose_name='Año de estreno')),
                ('pais', models.CharField(blank=True, max_length=200, verbose_name='País de origen')),
                ('fecha_funcion', models.CharField(blank=True, max_length=100, verbose_name='Fecha de función (texto)')),
                ('fecha_precisa', models.DateField(blank=True, null=True, verbose_name='Fecha exacta (si se conoce)')),
                ('hora', models.CharField(blank=True, max_length=50, verbose_name='Horario')),
                ('locacion', models.CharField(blank=True, max_length=300, verbose_name='Lugar de proyección')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo (largometraje/corto/documental/animación)')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Sinopsis / descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden dentro del ciclo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funciones', to='core.ciclo', verbose_name='Ciclo al que pertenece')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'ordering': ['ciclo__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del evento')),
                ('fecha', models.CharField(blank=True, max_length=100, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcion', verbose_name='Función relacionada')),
            ],
            options={
                'verbose_name': 'Evento especial',
                'verbose_name_plural': 'Eventos especiales',
                'ordering': ['fecha'],
            },
        ),
    ]
