# Generated by Django 4.2.16 on 2026-06-30 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del aviso')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('es_urgente', models.BooleanField(default=False, verbose_name='¿Es urgente?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('mostrar_resultados', models.BooleanField(default=True, verbose_name='Mostrar resultados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Texto de la opción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.encuesta')),
            ],
            options={
                'verbose_name': 'Opción de encuesta',
                'verbose_name_plural': 'Opciones de encuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL del logo')),
                ('sitio_web', models.URLField(blank=True, max_length=500, verbose_name='Sitio web')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('token_baja', models.CharField(blank=True, max_length=64, verbose_name='Token para darse de baja')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
        migrations.AddField(
            model_name='ciclo',
            name='imagen_path',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen del ciclo'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='poster_path',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del poster (TMDB)'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionencuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='Recaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.IntegerField(verbose_name='Monto (CLP)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Donante')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudaciones', to='core.funcion', verbose_name='Función')),
            ],
            options={
                'verbose_name': 'Recaudación',
                'verbose_name_plural': 'Recaudaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EnvioAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatarios_count', models.IntegerField(default=0, verbose_name='Cantidad de destinatarios')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='core.aviso')),
            ],
            options={
                'verbose_name': 'Envío de aviso',
                'verbose_name_plural': 'Envíos de avisos',
            },
        ),
        migrations.AddField(
            model_name='aviso',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcion', verbose_name='Función relacionada'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateTimeField(auto_now_add=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.funcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('usuario', 'encuesta'), name='un_voto_por_encuesta'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'funcion'), name='un_checkin_por_funcion'),
        ),
    ]
